version: "3"
services:
  discovery:
    container_name: eureka-docker
    image: eureka-docker
    restart: always
    build:
      context: ./eureka
      dockerfile: Dockerfile
    expose:
      - 8761
    ports:
      - 8761:8761
    networks:
      - stripomanija
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - stripomanija
  #mysql konekcije
  mysql:
    image: mysql:8.0.2
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: user-service
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - stripomanija
  mysql-comicbook:
    image: mysql:8.0.2
    container_name: mysql-comicbook
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: stripovi
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - stripomanija
  mysql-catalogue:
    image: mysql:8.0.2
    container_name: mysql-catalogue
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: katalozi
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - stripomanija
  mysql-rating:
    image: mysql:8.0.2
    container_name: mysql-rating
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: rating-service
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - stripomanija
  mysql-events:
    image: mysql:8.0.2
    container_name: mysql-events
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: system-events
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - stripomanija
  user-service:
    image: user-docker
    container_name: user-docker
    build:
      context: ./user-microservice
      dockerfile: Dockerfile
    expose:
      - 8085
    ports:
      - 8085:8085
    networks:
      - stripomanija
    restart: on-failure
    links:
      - discovery:eureka-docker
      - mysql:mysql
      - rabbitmq:rabbitmq
    depends_on:
      - mysql
      - discovery
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/user-service?useSSL=false&allowPublicKeyRetrieval=true'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_RABBITMQ_HOST: rabbitmq
  api-gateway:
    image: gateway-docker
    container_name: gateway-docker
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    expose:
      - 8086
    ports:
      - 8086:8086
    restart: on-failure
    links:
      - discovery:eureka-docker
    depends_on:
      - discovery
      - user-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    networks:
      - stripomanija
  comicbook-service:
    image: comicbook-docker
    container_name: comicbook-docker
    build:
      context: ./comicbook-microservice
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - 8083
    ports:
      - 8083:8083
    depends_on:
      - mysql-comicbook
      - discovery
    networks:
      - stripomanija
    environment:
      #mysql konekcija
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-comicbook:3306/stripovi?useSSL=false&allowPublicKeyRetrieval=true'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
  catalogue-service:
    image: catalogue-docker
    container_name: catalogue-docker
    build:
      context: ./catalogue-microservice
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - 8082
    ports:
      - 8082:8082
    links:
      - mysql-catalogue:mysql-catalogue
      - rabbitmq:rabbitmq
      - discovery:eureka-docker
      - user-service:user-docker
      - comicbook-service:comicbook-docker
    depends_on:
      - mysql-catalogue
      - rabbitmq
      - user-service
      - comicbook-service
      - discovery
    networks:
      - stripomanija
    environment:
      #mysql konekcija
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-catalogue:3306/katalozi?useSSL=false&allowPublicKeyRetrieval=true'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_RABBITMQ_HOST: rabbitmq
  rating-service:
    image: rating-service
    container_name: rating-service
    build:
      context: ./rating-service
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - 8081
    ports:
      - 8081:8081
    depends_on:
      - mysql-rating
      - discovery
      - comicbook-service
      - user-service
    networks:
      - stripomanija
    environment:
      #mysql konekcija
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-rating:3306/rating-service?useSSL=false&allowPublicKeyRetrieval=true'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
  stripomanija-frontend:
    container_name: stripomanija-frontend
    build:
      context: ./stripomanija-frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - stripomanija
  system-events:
    image: events-docker
    container_name: events-docker
    build:
      context: ./system-events
      dockerfile: Dockerfile
    expose:
      - 8084
    ports:
      - 8084:8084
    depends_on:
      - mysql-events
      - discovery
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-events:3306/system-events?useSSL=false'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    networks:
      - stripomanija

networks:
  stripomanija:
    driver: bridge
