server:
  port: 8086
spring:
  application:
    name: api-gateway
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 100000
ribbon:
  ReadTimeout: 6000

# zuul
zuul:
  host:
    socket-timeout-millis: 20000
    connect-timeout-millis: 20000
  routes:
    #user servis
    user:
      path: /user/**
      service-id: user-service
      strip-prefix: false
    #rating servis
    rating:
      path: /rating/**
      service-id: rating-service
      strip-prefix: false
    #katalog servis
    korisnik:
      path: /korisnik/**
      service-id: catalogue-service
      strip-prefix: false
    katalog:
      path: /katalog/**
      service-id: catalogue-service
      strip-prefix: false
    stripKatalog:
      path: /katalog/iz-kataloga/**
      service-id: catalogue-service
      strip-prefix: false
    #comicbook servis
    autor:
      path: /autor/**
      service-id: comicbook-service
      strip-prefix: false
    zanr:
      path: /zanr/**
      service-id: comicbook-service
      strip-prefix: false
    izdavac:
      path: /izdavac/**
      service-id: comicbook-service
      strip-prefix: false
    strip:
      path: /strip/**
      service-id: comicbook-service
      strip-prefix: false
  sensitive-headers:

# eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone:
        http://discovery:8761/eureka
