package catalogue.microsservice.cataloguemicroservice.grpc;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

public final class Events {
  private Events() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ActionType}
   */
  public enum ActionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CREATE = 0;</code>
     */
    CREATE(0),
    /**
     * <code>UPDATE = 1;</code>
     */
    UPDATE(1),
    /**
     * <code>DELETE = 2;</code>
     */
    DELETE(2),
    /**
     * <code>GET = 3;</code>
     */
    GET(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CREATE = 0;</code>
     */
    public static final int CREATE_VALUE = 0;
    /**
     * <code>UPDATE = 1;</code>
     */
    public static final int UPDATE_VALUE = 1;
    /**
     * <code>DELETE = 2;</code>
     */
    public static final int DELETE_VALUE = 2;
    /**
     * <code>GET = 3;</code>
     */
    public static final int GET_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ActionType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ActionType forNumber(int value) {
      switch (value) {
        case 0: return CREATE;
        case 1: return UPDATE;
        case 2: return DELETE;
        case 3: return GET;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ActionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
            public ActionType findValueByNumber(int number) {
              return ActionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Events.getDescriptor().getEnumTypes().get(0);
    }

    private static final ActionType[] VALUES = values();

    public static ActionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ActionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ActionType)
  }

  /**
   * Protobuf enum {@code ResponseType}
   */
  public enum ResponseType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <code>ERROR = 1;</code>
     */
    ERROR(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <code>ERROR = 1;</code>
     */
    public static final int ERROR_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ResponseType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ResponseType forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResponseType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
            public ResponseType findValueByNumber(int number) {
              return ResponseType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Events.getDescriptor().getEnumTypes().get(1);
    }

    private static final ResponseType[] VALUES = values();

    public static ResponseType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResponseType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ResponseType)
  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string timestamp = 1;</code>
     * @return The timestamp.
     */
    String getTimestamp();
    /**
     * <code>string timestamp = 1;</code>
     * @return The bytes for timestamp.
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <code>string nazivServisa = 2;</code>
     * @return The nazivServisa.
     */
    String getNazivServisa();
    /**
     * <code>string nazivServisa = 2;</code>
     * @return The bytes for nazivServisa.
     */
    com.google.protobuf.ByteString
        getNazivServisaBytes();

    /**
     * <code>int64 idKorisnik = 3;</code>
     * @return The idKorisnik.
     */
    long getIdKorisnik();

    /**
     * <code>.ActionType tipAkcije = 4;</code>
     * @return The enum numeric value on the wire for tipAkcije.
     */
    int getTipAkcijeValue();
    /**
     * <code>.ActionType tipAkcije = 4;</code>
     * @return The tipAkcije.
     */
    ActionType getTipAkcije();

    /**
     * <code>string nazivResursa = 5;</code>
     * @return The nazivResursa.
     */
    String getNazivResursa();
    /**
     * <code>string nazivResursa = 5;</code>
     * @return The bytes for nazivResursa.
     */
    com.google.protobuf.ByteString
        getNazivResursaBytes();
  }
  /**
   * Protobuf type {@code Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      timestamp_ = "";
      nazivServisa_ = "";
      tipAkcije_ = 0;
      nazivResursa_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Request();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              timestamp_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              nazivServisa_ = s;
              break;
            }
            case 24: {

              idKorisnik_ = input.readInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              tipAkcije_ = rawValue;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              nazivResursa_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Events.internal_static_Request_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Events.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Request.class, Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private volatile Object timestamp_;
    /**
     * <code>string timestamp = 1;</code>
     * @return The timestamp.
     */
    public String getTimestamp() {
      Object ref = timestamp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <code>string timestamp = 1;</code>
     * @return The bytes for timestamp.
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAZIVSERVISA_FIELD_NUMBER = 2;
    private volatile Object nazivServisa_;
    /**
     * <code>string nazivServisa = 2;</code>
     * @return The nazivServisa.
     */
    public String getNazivServisa() {
      Object ref = nazivServisa_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nazivServisa_ = s;
        return s;
      }
    }
    /**
     * <code>string nazivServisa = 2;</code>
     * @return The bytes for nazivServisa.
     */
    public com.google.protobuf.ByteString
        getNazivServisaBytes() {
      Object ref = nazivServisa_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nazivServisa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDKORISNIK_FIELD_NUMBER = 3;
    private long idKorisnik_;
    /**
     * <code>int64 idKorisnik = 3;</code>
     * @return The idKorisnik.
     */
    public long getIdKorisnik() {
      return idKorisnik_;
    }

    public static final int TIPAKCIJE_FIELD_NUMBER = 4;
    private int tipAkcije_;
    /**
     * <code>.ActionType tipAkcije = 4;</code>
     * @return The enum numeric value on the wire for tipAkcije.
     */
    public int getTipAkcijeValue() {
      return tipAkcije_;
    }
    /**
     * <code>.ActionType tipAkcije = 4;</code>
     * @return The tipAkcije.
     */
    public ActionType getTipAkcije() {
      @SuppressWarnings("deprecation")
      ActionType result = ActionType.valueOf(tipAkcije_);
      return result == null ? ActionType.UNRECOGNIZED : result;
    }

    public static final int NAZIVRESURSA_FIELD_NUMBER = 5;
    private volatile Object nazivResursa_;
    /**
     * <code>string nazivResursa = 5;</code>
     * @return The nazivResursa.
     */
    public String getNazivResursa() {
      Object ref = nazivResursa_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nazivResursa_ = s;
        return s;
      }
    }
    /**
     * <code>string nazivResursa = 5;</code>
     * @return The bytes for nazivResursa.
     */
    public com.google.protobuf.ByteString
        getNazivResursaBytes() {
      Object ref = nazivResursa_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nazivResursa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTimestampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timestamp_);
      }
      if (!getNazivServisaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nazivServisa_);
      }
      if (idKorisnik_ != 0L) {
        output.writeInt64(3, idKorisnik_);
      }
      if (tipAkcije_ != ActionType.CREATE.getNumber()) {
        output.writeEnum(4, tipAkcije_);
      }
      if (!getNazivResursaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, nazivResursa_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTimestampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timestamp_);
      }
      if (!getNazivServisaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nazivServisa_);
      }
      if (idKorisnik_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, idKorisnik_);
      }
      if (tipAkcije_ != ActionType.CREATE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, tipAkcije_);
      }
      if (!getNazivResursaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, nazivResursa_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Request)) {
        return super.equals(obj);
      }
      Request other = (Request) obj;

      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
      if (!getNazivServisa()
          .equals(other.getNazivServisa())) return false;
      if (getIdKorisnik()
          != other.getIdKorisnik()) return false;
      if (tipAkcije_ != other.tipAkcije_) return false;
      if (!getNazivResursa()
          .equals(other.getNazivResursa())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      hash = (37 * hash) + NAZIVSERVISA_FIELD_NUMBER;
      hash = (53 * hash) + getNazivServisa().hashCode();
      hash = (37 * hash) + IDKORISNIK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIdKorisnik());
      hash = (37 * hash) + TIPAKCIJE_FIELD_NUMBER;
      hash = (53 * hash) + tipAkcije_;
      hash = (37 * hash) + NAZIVRESURSA_FIELD_NUMBER;
      hash = (53 * hash) + getNazivResursa().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Events.internal_static_Request_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Events.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Request.class, Builder.class);
      }

      // Construct using Events.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        timestamp_ = "";

        nazivServisa_ = "";

        idKorisnik_ = 0L;

        tipAkcije_ = 0;

        nazivResursa_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Events.internal_static_Request_descriptor;
      }

      @Override
      public Request getDefaultInstanceForType() {
        return Request.getDefaultInstance();
      }

      @Override
      public Request build() {
        Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Request buildPartial() {
        Request result = new Request(this);
        result.timestamp_ = timestamp_;
        result.nazivServisa_ = nazivServisa_;
        result.idKorisnik_ = idKorisnik_;
        result.tipAkcije_ = tipAkcije_;
        result.nazivResursa_ = nazivResursa_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Request) {
          return mergeFrom((Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Request other) {
        if (other == Request.getDefaultInstance()) return this;
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (!other.getNazivServisa().isEmpty()) {
          nazivServisa_ = other.nazivServisa_;
          onChanged();
        }
        if (other.getIdKorisnik() != 0L) {
          setIdKorisnik(other.getIdKorisnik());
        }
        if (other.tipAkcije_ != 0) {
          setTipAkcijeValue(other.getTipAkcijeValue());
        }
        if (!other.getNazivResursa().isEmpty()) {
          nazivResursa_ = other.nazivResursa_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object timestamp_ = "";
      /**
       * <code>string timestamp = 1;</code>
       * @return The timestamp.
       */
      public String getTimestamp() {
        Object ref = timestamp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string timestamp = 1;</code>
       * @return The bytes for timestamp.
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {

        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 1;</code>
       * @param value The bytes for timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        timestamp_ = value;
        onChanged();
        return this;
      }

      private Object nazivServisa_ = "";
      /**
       * <code>string nazivServisa = 2;</code>
       * @return The nazivServisa.
       */
      public String getNazivServisa() {
        Object ref = nazivServisa_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nazivServisa_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string nazivServisa = 2;</code>
       * @return The bytes for nazivServisa.
       */
      public com.google.protobuf.ByteString
          getNazivServisaBytes() {
        Object ref = nazivServisa_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nazivServisa_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nazivServisa = 2;</code>
       * @param value The nazivServisa to set.
       * @return This builder for chaining.
       */
      public Builder setNazivServisa(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        nazivServisa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nazivServisa = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNazivServisa() {

        nazivServisa_ = getDefaultInstance().getNazivServisa();
        onChanged();
        return this;
      }
      /**
       * <code>string nazivServisa = 2;</code>
       * @param value The bytes for nazivServisa to set.
       * @return This builder for chaining.
       */
      public Builder setNazivServisaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        nazivServisa_ = value;
        onChanged();
        return this;
      }

      private long idKorisnik_ ;
      /**
       * <code>int64 idKorisnik = 3;</code>
       * @return The idKorisnik.
       */
      public long getIdKorisnik() {
        return idKorisnik_;
      }
      /**
       * <code>int64 idKorisnik = 3;</code>
       * @param value The idKorisnik to set.
       * @return This builder for chaining.
       */
      public Builder setIdKorisnik(long value) {

        idKorisnik_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 idKorisnik = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdKorisnik() {

        idKorisnik_ = 0L;
        onChanged();
        return this;
      }

      private int tipAkcije_ = 0;
      /**
       * <code>.ActionType tipAkcije = 4;</code>
       * @return The enum numeric value on the wire for tipAkcije.
       */
      public int getTipAkcijeValue() {
        return tipAkcije_;
      }
      /**
       * <code>.ActionType tipAkcije = 4;</code>
       * @param value The enum numeric value on the wire for tipAkcije to set.
       * @return This builder for chaining.
       */
      public Builder setTipAkcijeValue(int value) {
        tipAkcije_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ActionType tipAkcije = 4;</code>
       * @return The tipAkcije.
       */
      public ActionType getTipAkcije() {
        @SuppressWarnings("deprecation")
        ActionType result = ActionType.valueOf(tipAkcije_);
        return result == null ? ActionType.UNRECOGNIZED : result;
      }
      /**
       * <code>.ActionType tipAkcije = 4;</code>
       * @param value The tipAkcije to set.
       * @return This builder for chaining.
       */
      public Builder setTipAkcije(ActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        tipAkcije_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ActionType tipAkcije = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTipAkcije() {

        tipAkcije_ = 0;
        onChanged();
        return this;
      }

      private Object nazivResursa_ = "";
      /**
       * <code>string nazivResursa = 5;</code>
       * @return The nazivResursa.
       */
      public String getNazivResursa() {
        Object ref = nazivResursa_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nazivResursa_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string nazivResursa = 5;</code>
       * @return The bytes for nazivResursa.
       */
      public com.google.protobuf.ByteString
          getNazivResursaBytes() {
        Object ref = nazivResursa_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nazivResursa_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nazivResursa = 5;</code>
       * @param value The nazivResursa to set.
       * @return This builder for chaining.
       */
      public Builder setNazivResursa(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        nazivResursa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nazivResursa = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearNazivResursa() {

        nazivResursa_ = getDefaultInstance().getNazivResursa();
        onChanged();
        return this;
      }
      /**
       * <code>string nazivResursa = 5;</code>
       * @param value The bytes for nazivResursa to set.
       * @return This builder for chaining.
       */
      public Builder setNazivResursaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        nazivResursa_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Request)
    }

    // @@protoc_insertion_point(class_scope:Request)
    private static final Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Request();
    }

    public static Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @Override
    public Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string responseContent = 1;</code>
     * @return The responseContent.
     */
    String getResponseContent();
    /**
     * <code>string responseContent = 1;</code>
     * @return The bytes for responseContent.
     */
    com.google.protobuf.ByteString
        getResponseContentBytes();

    /**
     * <code>.ResponseType responseType = 2;</code>
     * @return The enum numeric value on the wire for responseType.
     */
    int getResponseTypeValue();
    /**
     * <code>.ResponseType responseType = 2;</code>
     * @return The responseType.
     */
    ResponseType getResponseType();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      responseContent_ = "";
      responseType_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              responseContent_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              responseType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Events.internal_static_Response_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Events.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Response.class, Builder.class);
    }

    public static final int RESPONSECONTENT_FIELD_NUMBER = 1;
    private volatile Object responseContent_;
    /**
     * <code>string responseContent = 1;</code>
     * @return The responseContent.
     */
    public String getResponseContent() {
      Object ref = responseContent_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        responseContent_ = s;
        return s;
      }
    }
    /**
     * <code>string responseContent = 1;</code>
     * @return The bytes for responseContent.
     */
    public com.google.protobuf.ByteString
        getResponseContentBytes() {
      Object ref = responseContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        responseContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSETYPE_FIELD_NUMBER = 2;
    private int responseType_;
    /**
     * <code>.ResponseType responseType = 2;</code>
     * @return The enum numeric value on the wire for responseType.
     */
    public int getResponseTypeValue() {
      return responseType_;
    }
    /**
     * <code>.ResponseType responseType = 2;</code>
     * @return The responseType.
     */
    public ResponseType getResponseType() {
      @SuppressWarnings("deprecation")
      ResponseType result = ResponseType.valueOf(responseType_);
      return result == null ? ResponseType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseContent_);
      }
      if (responseType_ != ResponseType.SUCCESS.getNumber()) {
        output.writeEnum(2, responseType_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseContent_);
      }
      if (responseType_ != ResponseType.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, responseType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Response)) {
        return super.equals(obj);
      }
      Response other = (Response) obj;

      if (!getResponseContent()
          .equals(other.getResponseContent())) return false;
      if (responseType_ != other.responseType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getResponseContent().hashCode();
      hash = (37 * hash) + RESPONSETYPE_FIELD_NUMBER;
      hash = (53 * hash) + responseType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Events.internal_static_Response_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Events.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Response.class, Builder.class);
      }

      // Construct using Events.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        responseContent_ = "";

        responseType_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Events.internal_static_Response_descriptor;
      }

      @Override
      public Response getDefaultInstanceForType() {
        return Response.getDefaultInstance();
      }

      @Override
      public Response build() {
        Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Response buildPartial() {
        Response result = new Response(this);
        result.responseContent_ = responseContent_;
        result.responseType_ = responseType_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Response) {
          return mergeFrom((Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Response other) {
        if (other == Response.getDefaultInstance()) return this;
        if (!other.getResponseContent().isEmpty()) {
          responseContent_ = other.responseContent_;
          onChanged();
        }
        if (other.responseType_ != 0) {
          setResponseTypeValue(other.getResponseTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object responseContent_ = "";
      /**
       * <code>string responseContent = 1;</code>
       * @return The responseContent.
       */
      public String getResponseContent() {
        Object ref = responseContent_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          responseContent_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string responseContent = 1;</code>
       * @return The bytes for responseContent.
       */
      public com.google.protobuf.ByteString
          getResponseContentBytes() {
        Object ref = responseContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          responseContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseContent = 1;</code>
       * @param value The responseContent to set.
       * @return This builder for chaining.
       */
      public Builder setResponseContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        responseContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responseContent = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseContent() {

        responseContent_ = getDefaultInstance().getResponseContent();
        onChanged();
        return this;
      }
      /**
       * <code>string responseContent = 1;</code>
       * @param value The bytes for responseContent to set.
       * @return This builder for chaining.
       */
      public Builder setResponseContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        responseContent_ = value;
        onChanged();
        return this;
      }

      private int responseType_ = 0;
      /**
       * <code>.ResponseType responseType = 2;</code>
       * @return The enum numeric value on the wire for responseType.
       */
      public int getResponseTypeValue() {
        return responseType_;
      }
      /**
       * <code>.ResponseType responseType = 2;</code>
       * @param value The enum numeric value on the wire for responseType to set.
       * @return This builder for chaining.
       */
      public Builder setResponseTypeValue(int value) {
        responseType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ResponseType responseType = 2;</code>
       * @return The responseType.
       */
      public ResponseType getResponseType() {
        @SuppressWarnings("deprecation")
        ResponseType result = ResponseType.valueOf(responseType_);
        return result == null ? ResponseType.UNRECOGNIZED : result;
      }
      /**
       * <code>.ResponseType responseType = 2;</code>
       * @param value The responseType to set.
       * @return This builder for chaining.
       */
      public Builder setResponseType(ResponseType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        responseType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ResponseType responseType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseType() {

        responseType_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Response();
    }

    public static Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @Override
    public Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014events.proto\"|\n\007Request\022\021\n\ttimestamp\030\001" +
      " \001(\t\022\024\n\014nazivServisa\030\002 \001(\t\022\022\n\nidKorisnik" +
      "\030\003 \001(\003\022\036\n\ttipAkcije\030\004 \001(\0162\013.ActionType\022\024" +
      "\n\014nazivResursa\030\005 \001(\t\"H\n\010Response\022\027\n\017resp" +
      "onseContent\030\001 \001(\t\022#\n\014responseType\030\002 \001(\0162" +
      "\r.ResponseType*9\n\nActionType\022\n\n\006CREATE\020\000" +
      "\022\n\n\006UPDATE\020\001\022\n\n\006DELETE\020\002\022\007\n\003GET\020\003*&\n\014Res" +
      "ponseType\022\013\n\007SUCCESS\020\000\022\t\n\005ERROR\020\0012*\n\006act" +
      "ion\022 \n\tlogAction\022\010.Request\032\t.Responseb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new String[] { "Timestamp", "NazivServisa", "IdKorisnik", "TipAkcije", "NazivResursa", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new String[] { "ResponseContent", "ResponseType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
